updated yml files

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,4 +1,4 @@
-name: React.js CI/CD Pipeline 
+name: React App CI/CD
 on:
   push:
     branches:
@@ -7,28 +7,22 @@ on:
     branches:
       - dev
 jobs:
-  build-test-deploy:
+  build:
     runs-on: ubuntu-20.04
-
     steps:
-      - name: Checkout Code
+      - name: Checkout code
         uses: actions/checkout@v2
-        with:
-          node-version: '16'
-
-      - name: Set Up Node.js
+      - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '16'
-
-      - name: Install Dependencies
+          node-version: '18'
+      - name: Check for "build" script
+        run: |
+          if ! npm run -s build --if-present; then
+            echo "No 'build' script found in package.json or it failed to run."
+            exit 0
+          fi
+      - name: Install Packages
         run: npm install
-
-      - name: Build
-        working-directory: ./etaka
-        run: npm run build
-
-      - name: Run Test
+      - name: Run Tests
         run: npm test
-    
-  
